version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "ggcom_db"
      MYSQL_USER: ggcom_user
      MYSQL_PASSWORD: ggcom_pass
    networks:
      - etl_dev_ggcom
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: ggcom_user
      PMA_PASSWORD: ggcom_pass
    ports:
      - "8080:80"
    networks:
      - etl_dev_ggcom
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  etl_dev_ggcom:
    external: true
